# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Administrator\Desktop\lzx\kylin430\ui_kylin430.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(901, 600)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 921, 461))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 20, 171, 341))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(10, 90, 152, 151))
        self.formLayoutWidget_8.setObjectName("formLayoutWidget_8")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formLayoutWidget_8)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_38 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_38.setObjectName("label_38")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.comboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget_8)
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.label_39 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_39.setObjectName("label_39")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.comboBox_3 = QtWidgets.QComboBox(self.formLayoutWidget_8)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_3)
        self.label_40 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_40.setObjectName("label_40")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.comboBox_4 = QtWidgets.QComboBox(self.formLayoutWidget_8)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_4)
        self.label_41 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_41.setObjectName("label_41")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.comboBox_5 = QtWidgets.QComboBox(self.formLayoutWidget_8)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_5)
        self.label_42 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_42.setObjectName("label_42")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.comboBox_6 = QtWidgets.QComboBox(self.formLayoutWidget_8)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comboBox_6)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 250, 151, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.label_43 = QtWidgets.QLabel(self.groupBox_2)
        self.label_43.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.label_43.setObjectName("label_43")
        self.formLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget_9.setGeometry(QtCore.QRect(10, 20, 151, 31))
        self.formLayoutWidget_9.setObjectName("formLayoutWidget_9")
        self.formLayout_9 = QtWidgets.QFormLayout(self.formLayoutWidget_9)
        self.formLayout_9.setContentsMargins(0, 0, 0, 0)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_9)
        self.label_17.setObjectName("label_17")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.pushButton_4_portcheck = QtWidgets.QPushButton(self.formLayoutWidget_9)
        self.pushButton_4_portcheck.setObjectName("pushButton_4_portcheck")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_4_portcheck)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(930, 470, 101, 31))
        self.label.setObjectName("label")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(430, 20, 201, 341))
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayoutWidget_45 = QtWidgets.QWidget(self.groupBox_5)
        self.formLayoutWidget_45.setGeometry(QtCore.QRect(20, 90, 160, 61))
        self.formLayoutWidget_45.setObjectName("formLayoutWidget_45")
        self.formLayout_46 = QtWidgets.QFormLayout(self.formLayoutWidget_45)
        self.formLayout_46.setContentsMargins(0, 0, 0, 0)
        self.formLayout_46.setObjectName("formLayout_46")
        self.label_202 = QtWidgets.QLabel(self.formLayoutWidget_45)
        self.label_202.setObjectName("label_202")
        self.formLayout_46.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_202)
        self.label_203 = QtWidgets.QLabel(self.formLayoutWidget_45)
        self.label_203.setObjectName("label_203")
        self.formLayout_46.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_203)
        self.spinBox_5 = QtWidgets.QSpinBox(self.formLayoutWidget_45)
        self.spinBox_5.setObjectName("spinBox_5")
        self.formLayout_46.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_5)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_45)
        self.lineEdit.setInputMask("")
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_46.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_5.setGeometry(QtCore.QRect(50, 240, 91, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(230, 20, 181, 341))
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayoutWidget_43 = QtWidgets.QWidget(self.groupBox_4)
        self.formLayoutWidget_43.setGeometry(QtCore.QRect(10, 90, 160, 61))
        self.formLayoutWidget_43.setObjectName("formLayoutWidget_43")
        self.formLayout_44 = QtWidgets.QFormLayout(self.formLayoutWidget_43)
        self.formLayout_44.setContentsMargins(0, 0, 0, 0)
        self.formLayout_44.setObjectName("formLayout_44")
        self.label_198 = QtWidgets.QLabel(self.formLayoutWidget_43)
        self.label_198.setObjectName("label_198")
        self.formLayout_44.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_198)
        self.label_199 = QtWidgets.QLabel(self.formLayoutWidget_43)
        self.label_199.setObjectName("label_199")
        self.formLayout_44.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_199)
        self.spinBox = QtWidgets.QSpinBox(self.formLayoutWidget_43)
        self.spinBox.setSuffix("")
        self.spinBox.setMaximum(134217731)
        self.spinBox.setDisplayIntegerBase(16)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_44.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.spinBox_2 = QtWidgets.QSpinBox(self.formLayoutWidget_43)
        self.spinBox_2.setMaximum(31)
        self.spinBox_2.setObjectName("spinBox_2")
        self.formLayout_44.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_2)
        self.pushButton_setreg = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_setreg.setGeometry(QtCore.QRect(40, 240, 101, 23))
        self.pushButton_setreg.setObjectName("pushButton_setreg")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(730, 370, 131, 41))
        self.label_2.setObjectName("label_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(670, 20, 201, 341))
        self.groupBox_6.setObjectName("groupBox_6")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_6)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 30, 171, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox_7 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_7)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.comboBox_8 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_8)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.comboBox_9 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_9)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_6)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 160, 171, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.spinBox_3 = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout.addWidget(self.spinBox_3)
        self.comboBox_10 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_10)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_4)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 0, 191, 100))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.comboBox_stream_type = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.comboBox_stream_type.setObjectName("comboBox_stream_type")
        self.comboBox_stream_type.addItem("")
        self.comboBox_stream_type.addItem("")
        self.comboBox_stream_type.addItem("")
        self.comboBox_stream_type.addItem("")
        self.comboBox_stream_type.addItem("")
        self.comboBox_stream_type.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_stream_type)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineEdit_ClockLevel = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_ClockLevel.setObjectName("lineEdit_ClockLevel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_ClockLevel)
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_23.setObjectName("label_23")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.label_24 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_24.setObjectName("label_24")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.lineEdit_Priority1 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_Priority1.setObjectName("lineEdit_Priority1")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Priority1)
        self.lineEdit_Priority2 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.lineEdit_Priority2.setObjectName("lineEdit_Priority2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Priority2)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 110, 296, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.lineEdit_Smac0 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_Smac0.setObjectName("lineEdit_Smac0")
        self.horizontalLayout_2.addWidget(self.lineEdit_Smac0)
        self.lineEdit_Smac1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_Smac1.setObjectName("lineEdit_Smac1")
        self.horizontalLayout_2.addWidget(self.lineEdit_Smac1)
        self.lineEdit_Smac2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_Smac2.setObjectName("lineEdit_Smac2")
        self.horizontalLayout_2.addWidget(self.lineEdit_Smac2)
        self.lineEdit_Smac3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_Smac3.setObjectName("lineEdit_Smac3")
        self.horizontalLayout_2.addWidget(self.lineEdit_Smac3)
        self.lineEdit_Smac4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_Smac4.setObjectName("lineEdit_Smac4")
        self.horizontalLayout_2.addWidget(self.lineEdit_Smac4)
        self.lineEdit_Smac5 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_Smac5.setObjectName("lineEdit_Smac5")
        self.horizontalLayout_2.addWidget(self.lineEdit_Smac5)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 170, 740, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.lineEdit_SIP = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_SIP.setObjectName("lineEdit_SIP")
        self.horizontalLayout_3.addWidget(self.lineEdit_SIP)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(350, 110, 530, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_4.addWidget(self.label_18)
        self.lineEdit_PortId = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEdit_PortId.setObjectName("lineEdit_PortId")
        self.horizontalLayout_4.addWidget(self.lineEdit_PortId)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_3.setGeometry(QtCore.QRect(480, 0, 181, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 160, 80))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_unicast = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        self.radioButton_unicast.setObjectName("radioButton_unicast")
        self.horizontalLayout_5.addWidget(self.radioButton_unicast)
        self.radioButton_multicase = QtWidgets.QRadioButton(self.horizontalLayoutWidget_5)
        self.radioButton_multicase.setObjectName("radioButton_multicase")
        self.horizontalLayout_5.addWidget(self.radioButton_multicase)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_8.setGeometry(QtCore.QRect(20, 220, 761, 81))
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_8)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 160, 31))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButton_3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_6)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_6.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_6)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_6.addWidget(self.radioButton_4)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(30, 260, 530, 41))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_7.addWidget(self.label_19)
        self.lineEdit_sourcePortId = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.lineEdit_sourcePortId.setObjectName("lineEdit_sourcePortId")
        self.horizontalLayout_7.addWidget(self.lineEdit_sourcePortId)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_9.setGeometry(QtCore.QRect(20, 310, 861, 121))
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_9)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 20, 291, 80))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_8)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_8.addWidget(self.checkBox)
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.horizontalLayout_8.addWidget(self.lineEdit_48)
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_8.addWidget(self.label_20)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.horizontalLayout_8.addWidget(self.lineEdit_49)
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_8.addWidget(self.label_21)
        self.lineEdit_50 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.horizontalLayout_8.addWidget(self.lineEdit_50)
        self.label_22 = QtWidgets.QLabel(self.groupBox_9)
        self.label_22.setGeometry(QtCore.QRect(450, 50, 391, 31))
        self.label_22.setObjectName("label_22")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_10.setGeometry(QtCore.QRect(270, 0, 171, 101))
        self.groupBox_10.setObjectName("groupBox_10")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_10)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 151, 81))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.checkBox_2 = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        self.checkBox_2.setObjectName("checkBox_2")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        self.checkBox_3.setObjectName("checkBox_3")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        self.checkBox_4.setObjectName("checkBox_4")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkBox_4)
        self.lineEdit_53 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_53)
        self.lineEdit_54 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_54)
        self.lineEdit_55 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_55)
        self.groupBox = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox.setGeometry(QtCore.QRect(690, 0, 191, 101))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 173, 80))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.comboBox_announce_rate = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.comboBox_announce_rate.setObjectName("comboBox_announce_rate")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.comboBox_announce_rate.addItem("")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_announce_rate)
        self.comboBox_event_rate = QtWidgets.QComboBox(self.formLayoutWidget_3)
        self.comboBox_event_rate.setObjectName("comboBox_event_rate")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.comboBox_event_rate.addItem("")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_event_rate)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(340, 30, 211, 341))
        self.groupBox_7.setObjectName("groupBox_7")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_9.setGeometry(QtCore.QRect(50, 80, 111, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_10.setGeometry(QtCore.QRect(20, 240, 75, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_11.setGeometry(QtCore.QRect(120, 240, 75, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.tabWidget.addTab(self.tab_2, "")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser.setGeometry(QtCore.QRect(60, 460, 256, 111))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(590, 460, 256, 111))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(420, 500, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser.raise_()
        self.textBrowser_2.raise_()
        self.pushButton.raise_()
        self.tabWidget.raise_()
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 901, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "串口设置"))
        self.label_38.setText(_translate("MainWindow", "串口选择："))
        self.label_39.setText(_translate("MainWindow", "波特率："))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "9600"))
        self.label_40.setText(_translate("MainWindow", "数据位："))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "8"))
        self.label_41.setText(_translate("MainWindow", "校验位："))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "N"))
        self.label_42.setText(_translate("MainWindow", "停止位："))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "打开串口"))
        self.pushButton_3.setText(_translate("MainWindow", "关闭串口"))
        self.label_43.setText(_translate("MainWindow", "Serial Port:"))
        self.label_17.setText(_translate("MainWindow", "串口检测："))
        self.pushButton_4_portcheck.setText(_translate("MainWindow", "检测串口"))
        self.label.setText(_translate("MainWindow", "VERSION：1.0"))
        self.groupBox_5.setTitle(_translate("MainWindow", "寄存器读操作"))
        self.label_202.setText(_translate("MainWindow", "寄存器"))
        self.label_203.setText(_translate("MainWindow", "获取值"))
        self.lineEdit.setText(_translate("MainWindow", "0x"))
        self.pushButton_5.setText(_translate("MainWindow", "读值"))
        self.groupBox_4.setTitle(_translate("MainWindow", "寄存器写操作"))
        self.label_198.setText(_translate("MainWindow", "寄存器"))
        self.label_199.setText(_translate("MainWindow", "配置值"))
        self.spinBox.setPrefix(_translate("MainWindow", "0x", "ffffffff"))
        self.pushButton_setreg.setText(_translate("MainWindow", "写值"))
        self.label_2.setText(_translate("MainWindow", "Version:       1.0"))
        self.groupBox_6.setTitle(_translate("MainWindow", "功能操作"))
        self.label_3.setText(_translate("MainWindow", "Irig_B"))
        self.comboBox.setItemText(0, _translate("MainWindow", "enable"))
        self.comboBox.setItemText(1, _translate("MainWindow", "disable"))
        self.label_4.setText(_translate("MainWindow", "1pps_Tod"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "enable"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "disable"))
        self.label_5.setText(_translate("MainWindow", "Ptp_0"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "enable"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "disable"))
        self.label_6.setText(_translate("MainWindow", "Ptp_1"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "enable"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "disable"))
        self.label_7.setText(_translate("MainWindow", "EsmcCode"))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "enable"))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "disable"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "config"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "clk"))
        self.label_8.setText(_translate("MainWindow", "流类型"))
        self.comboBox_stream_type.setItemText(0, _translate("MainWindow", "以太网L2"))
        self.comboBox_stream_type.setItemText(1, _translate("MainWindow", "IPV4"))
        self.comboBox_stream_type.setItemText(2, _translate("MainWindow", "IPV6"))
        self.comboBox_stream_type.setItemText(3, _translate("MainWindow", "802.3的L2"))
        self.comboBox_stream_type.setItemText(4, _translate("MainWindow", "802.3的IPV4"))
        self.comboBox_stream_type.setItemText(5, _translate("MainWindow", "802.3的IPV6"))
        self.label_9.setText(_translate("MainWindow", "ClockLevel"))
        self.label_23.setText(_translate("MainWindow", "Priority1"))
        self.label_24.setText(_translate("MainWindow", "Priority2"))
        self.label_12.setText(_translate("MainWindow", "SMAC"))
        self.label_13.setText(_translate("MainWindow", "SIP"))
        self.label_18.setText(_translate("MainWindow", "本地PortId"))
        self.groupBox_3.setTitle(_translate("MainWindow", "单播组播模式"))
        self.radioButton_unicast.setText(_translate("MainWindow", "单播"))
        self.radioButton_multicase.setText(_translate("MainWindow", "组播"))
        self.groupBox_8.setTitle(_translate("MainWindow", "选源模式"))
        self.radioButton_3.setText(_translate("MainWindow", "自动模式"))
        self.radioButton_4.setText(_translate("MainWindow", "手动模式"))
        self.label_19.setText(_translate("MainWindow", "SourcePortId"))
        self.groupBox_9.setTitle(_translate("MainWindow", "32个flow"))
        self.checkBox.setText(_translate("MainWindow", "Flow0"))
        self.label_11.setText(_translate("MainWindow", "dmac"))
        self.label_20.setText(_translate("MainWindow", "dip"))
        self.label_21.setText(_translate("MainWindow", "vlan"))
        self.label_22.setText(_translate("MainWindow", "因为白名单必须填写dmac和dip；组播不用填写vlan，单播必须填写"))
        self.groupBox_10.setTitle(_translate("MainWindow", "组播vlan"))
        self.checkBox_2.setText(_translate("MainWindow", "外层Tpid"))
        self.checkBox_3.setText(_translate("MainWindow", "外层vlan"))
        self.checkBox_4.setText(_translate("MainWindow", "内层vlan"))
        self.groupBox.setTitle(_translate("MainWindow", "报文发送速率"))
        self.label_14.setText(_translate("MainWindow", "ANNOUNCE发送速率"))
        self.label_15.setText(_translate("MainWindow", "EVENT发送速率"))
        self.comboBox_announce_rate.setItemText(0, _translate("MainWindow", "-14"))
        self.comboBox_announce_rate.setItemText(1, _translate("MainWindow", "-13"))
        self.comboBox_announce_rate.setItemText(2, _translate("MainWindow", "-12"))
        self.comboBox_announce_rate.setItemText(3, _translate("MainWindow", "-11"))
        self.comboBox_announce_rate.setItemText(4, _translate("MainWindow", "-10"))
        self.comboBox_announce_rate.setItemText(5, _translate("MainWindow", "-9"))
        self.comboBox_announce_rate.setItemText(6, _translate("MainWindow", "-8"))
        self.comboBox_announce_rate.setItemText(7, _translate("MainWindow", "-7"))
        self.comboBox_announce_rate.setItemText(8, _translate("MainWindow", "-6"))
        self.comboBox_announce_rate.setItemText(9, _translate("MainWindow", "-5"))
        self.comboBox_announce_rate.setItemText(10, _translate("MainWindow", "-4"))
        self.comboBox_announce_rate.setItemText(11, _translate("MainWindow", "-3"))
        self.comboBox_announce_rate.setItemText(12, _translate("MainWindow", "-2"))
        self.comboBox_announce_rate.setItemText(13, _translate("MainWindow", "-1"))
        self.comboBox_announce_rate.setItemText(14, _translate("MainWindow", "0"))
        self.comboBox_announce_rate.setItemText(15, _translate("MainWindow", "1"))
        self.comboBox_announce_rate.setItemText(16, _translate("MainWindow", "2"))
        self.comboBox_announce_rate.setItemText(17, _translate("MainWindow", "3"))
        self.comboBox_announce_rate.setItemText(18, _translate("MainWindow", "4"))
        self.comboBox_announce_rate.setItemText(19, _translate("MainWindow", "5"))
        self.comboBox_announce_rate.setItemText(20, _translate("MainWindow", "6"))
        self.comboBox_announce_rate.setItemText(21, _translate("MainWindow", "7"))
        self.comboBox_announce_rate.setItemText(22, _translate("MainWindow", "8"))
        self.comboBox_announce_rate.setItemText(23, _translate("MainWindow", "9"))
        self.comboBox_announce_rate.setItemText(24, _translate("MainWindow", "10"))
        self.comboBox_event_rate.setItemText(0, _translate("MainWindow", "-14"))
        self.comboBox_event_rate.setItemText(1, _translate("MainWindow", "-13"))
        self.comboBox_event_rate.setItemText(2, _translate("MainWindow", "-12"))
        self.comboBox_event_rate.setItemText(3, _translate("MainWindow", "-11"))
        self.comboBox_event_rate.setItemText(4, _translate("MainWindow", "-10"))
        self.comboBox_event_rate.setItemText(5, _translate("MainWindow", "-9"))
        self.comboBox_event_rate.setItemText(6, _translate("MainWindow", "-8"))
        self.comboBox_event_rate.setItemText(7, _translate("MainWindow", "-7"))
        self.comboBox_event_rate.setItemText(8, _translate("MainWindow", "-6"))
        self.comboBox_event_rate.setItemText(9, _translate("MainWindow", "-5"))
        self.comboBox_event_rate.setItemText(10, _translate("MainWindow", "-4"))
        self.comboBox_event_rate.setItemText(11, _translate("MainWindow", "-3"))
        self.comboBox_event_rate.setItemText(12, _translate("MainWindow", "-2"))
        self.comboBox_event_rate.setItemText(13, _translate("MainWindow", "-1"))
        self.comboBox_event_rate.setItemText(14, _translate("MainWindow", "0"))
        self.comboBox_event_rate.setItemText(15, _translate("MainWindow", "1"))
        self.comboBox_event_rate.setItemText(16, _translate("MainWindow", "2"))
        self.comboBox_event_rate.setItemText(17, _translate("MainWindow", "3"))
        self.comboBox_event_rate.setItemText(18, _translate("MainWindow", "4"))
        self.comboBox_event_rate.setItemText(19, _translate("MainWindow", "5"))
        self.comboBox_event_rate.setItemText(20, _translate("MainWindow", "6"))
        self.comboBox_event_rate.setItemText(21, _translate("MainWindow", "7"))
        self.comboBox_event_rate.setItemText(22, _translate("MainWindow", "8"))
        self.comboBox_event_rate.setItemText(23, _translate("MainWindow", "9"))
        self.comboBox_event_rate.setItemText(24, _translate("MainWindow", "10"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "ptp_0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "ptp_1"))
        self.groupBox_7.setTitle(_translate("MainWindow", "文件操作"))
        self.pushButton_9.setToolTip(_translate("MainWindow", "<html><head/><body><p>生成文件kylin530_config.h</p></body></html>"))
        self.pushButton_9.setText(_translate("MainWindow", "生成文件"))
        self.pushButton_10.setToolTip(_translate("MainWindow", "<html><head/><body><p>导出默认文件名是conf1.h</p></body></html>"))
        self.pushButton_10.setText(_translate("MainWindow", "导出1"))
        self.pushButton_11.setToolTip(_translate("MainWindow", "<html><head/><body><p>导出默认文件名是conf2.h</p></body></html>"))
        self.pushButton_11.setText(_translate("MainWindow", "导出2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "misc"))
        self.pushButton.setText(_translate("MainWindow", "清除"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
